# Generated by Django 4.1.7 on 2023-03-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notifcation_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_link',
            field=models.URLField(default='/'),
        ),
    ]
