# Generated by Django 4.1.7 on 2023-03-09 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0005_remove_comment_new_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycomments', to=settings.AUTH_USER_MODEL),
        ),
    ]
