# Generated by Django 4.1.7 on 2023-03-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_comentee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
