# Generated by Django 4.1.7 on 2023-03-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(default='homes/default.png', upload_to='homes'),
        ),
    ]
