# Generated by Django 4.1.7 on 2023-03-09 02:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_home_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='price',
        ),
        migrations.AddField(
            model_name='home',
            name='baths',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='home',
            name='beds',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='home',
            name='guests',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='home',
            name='rating_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='home',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='homes.home'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='homes.home')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_images')),
                ('alt', models.CharField(max_length=50)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homes.home')),
            ],
        ),
    ]
