# Generated by Django 4.1.7 on 2023-03-09 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_remove_home_price_home_baths_home_beds_home_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2023, 3, 16)),
        ),
    ]
