# Generated by Django 4.1.7 on 2023-03-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_alter_images_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
