# Generated by Django 4.1.7 on 2023-04-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_alter_reservation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
