# Generated by Django 4.1.7 on 2023-03-09 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_rating_number_user_rating_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('\\d{9}', message='Phone number must be 9 digits long and in the following format: 123456789')], verbose_name='phone number'),
        ),
    ]
